// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_500_points = "CgkI-aCz3OcYEAIQCA"; // <GPGSID>
        public const string achievement_5_levels = "CgkI-aCz3OcYEAIQCw"; // <GPGSID>
        public const string leaderboard_infinity_mode = "CgkI-aCz3OcYEAIQAQ"; // <GPGSID>
        public const string achievement_300_points = "CgkI-aCz3OcYEAIQBw"; // <GPGSID>
        public const string achievement_25_points = "CgkI-aCz3OcYEAIQAA"; // <GPGSID>
        public const string achievement_40_levels = "CgkI-aCz3OcYEAIQDw"; // <GPGSID>
        public const string achievement_all_levels_complete = "CgkI-aCz3OcYEAIQEA"; // <GPGSID>
        public const string achievement_30_levels = "CgkI-aCz3OcYEAIQDg"; // <GPGSID>
        public const string achievement_buy_one_board_from_store = "CgkI-aCz3OcYEAIQAg"; // <GPGSID>
        public const string achievement_5_boards = "CgkI-aCz3OcYEAIQCg"; // <GPGSID>
        public const string achievement_100_points = "CgkI-aCz3OcYEAIQBQ"; // <GPGSID>
        public const string achievement_200_points = "CgkI-aCz3OcYEAIQBg"; // <GPGSID>
        public const string achievement_3_boards = "CgkI-aCz3OcYEAIQCQ"; // <GPGSID>
        public const string achievement_20_levels = "CgkI-aCz3OcYEAIQDQ"; // <GPGSID>
        public const string achievement_75_points = "CgkI-aCz3OcYEAIQBA"; // <GPGSID>
        public const string achievement_10_levels = "CgkI-aCz3OcYEAIQDA"; // <GPGSID>
        public const string achievement_50_points = "CgkI-aCz3OcYEAIQAw"; // <GPGSID>

}

